### ISSUE TITLE
How to set voxel size in Python?

### ISSUE THREAD

**Issue by Dr-QTDS** [imaris/ImarisWriter#14]

**Comment by imaris** [comment]
Voxel size can be computed from the image extents, conversely, you can setup image extents for specific voxel size.

This sets voxel size equal to 1 micrometer in x, y, z:
`image_extents = PW.ImageExtents(0, 0, 0, image_size.x, image_size.y, image_size.z)`

This is a more general code to set a specific voxel size (`image_max = image_min + voxel_size * image_size`):
`image_extents = PW.ImageExtents(image_min.x, image_min.y, image_min.z,
  image_min.x + voxel_size.x * image_size.x,
  image_min.y + voxel_size.y * image_size.y,
  image_min.z + voxel_size.z * image_size.z)`
The image position (`image_min`) is typically set to zero, but can be changed if the image is acquired through a moving stage, and may be necessary for stitching.

**Comment by Dr-QTDS** [comment]
Thanks! The answer solved the question.
